version: '3.2'
services:
  wildfly:
    build:
      context: ../../builds/wildfly-dist
      args:
        - KEYCLOAK_URI_ARG=${KEYCLOAK_URI_ARG}
    container_name: wildfly-${LONG_APP_NAME_LOWER}
    hostname: wildfly-${LONG_APP_NAME_LOWER}
    environment:
     - ADMIN_USER=admin
     - ADMIN_PASSWORD=admin
    ports:
     - ${WILDFLY_PORT}:8080
     - ${WILDFLY_ADMIN_PORT}:9990
    volumes:
     - ${WILDFLY_DEPLOY_DIR}:/opt/jboss/wildfly/standalone/deployments
     - ${WILDFLY_LIB_DIR}/backoffice.jar:/opt/jboss/wildfly/standalone/lib/backoffice.jar:ro
     #- ${WILDFLY_STANDALONE_CONFIGURATION_DIR}:/opt/jboss/wildfly/standalone/configuration
     - ${WILDFLY_CONFIG_DIR}:/opt/jboss/webapps/config
     - /app/scsp:/app/scsp
    depends_on:
      - keycloak
      - app-db
  keycloak:
    build:
      context: ../../builds/keycloak-dist
    container_name: keycloak-${LONG_APP_NAME_LOWER}
    hostname: keycloak-${LONG_APP_NAME_LOWER}
    environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
     - KEYCLOAK_IMPORT=/tmp/import-goib-realm.json
    ports:
     - ${KEYCLOAK_PORT}:8180
    volumes: 
      - ../../builds/keycloak-dist/keycloak/conf/import-goib-realm.json:/tmp/import-goib-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KEYCLOAK_URI_ARG}/auth/realms/GOIB"]
      interval: 10s
      timeout: 10s
      retries: 5
  app-db:
    image: postgres:9.5-alpine
    #build:
    #  context: ../../builds/postgresql-dist
    #build:
    #  context: ../../builds/postgresql-dist
    container_name: ${LONG_APP_NAME_LOWER}-pg
    hostname: ${LONG_APP_NAME_LOWER}-pg
    restart: always
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ../../builds/postgresql-dist/postgresql/bin/docker-entrypoint-initdb.d/00_initdb.sh:/docker-entrypoint-initdb.d/00_initdb.sh:ro
      - /app/docker/postgresql/${LONG_APP_NAME_LOWER}/data:/var/lib/postgresql/data
      - /app/docker/postgresql/${LONG_APP_NAME_LOWER}/backups:/app/postgresql/backups
      #- ../../builds/postgresql-dist/postgresql/tablespaces/${LONG_APP_NAME_LOWER}:/var/lib/postgresql/app/tablespaces
      #- ../../builds/postgresql-dist/postgresql/backups/${LONG_APP_NAME_LOWER}:/var/lib/postgresql/app/backups
    environment:
      - POSTGRES_PASSWORD=postgres
      - LONG_APP_NAME=${LONG_APP_NAME_LOWER}
      - SHORT_APP_NAME=${SHORT_APP_NAME_LOWER}
      - PGTABLESPACES=/var/lib/postgresql/data/tablespaces
  nginx:
    image: nginx
    container_name: nginx-${LONG_APP_NAME_LOWER}
    hostname: nginx-${LONG_APP_NAME_LOWER}
    restart: always
    ports:
      - ${NGINX_SERVER_HTTP_PORT}:80
      - ${NGINX_SERVER_HTTPS_PORT}:443
    volumes:
      - ../../builds/nginx-dist/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../builds/nginx-dist/nginx/bin/docker-entrypoint.d/nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh:ro
    depends_on:
      - wildfly
      - keycloak
      - app-db


    
